### ISSUE TITLE
Tag stable releases

### ISSUE THREAD

**Issue by sjackman** [Victorian-Bioinformatics-Consortium/prokka#12]
Tagging stable releases could be a good way to download the Prokka code without downloading the large databases.

**Comment by tseemann** [comment]
@nsoranzo  I'm not going to include Genus databases anymore. They are unreliable. If you want to use one, get the Genbank file(s) yourself (of the ones you trust) and use prokka-genbank_to_fasta_db to create a .faa file and pass that to --proteins. Or just make a multi-genbank and give it straight to the --proteins (new feature in 1.11-dev).

**Comment by sjackman** [comment]
Sourceforge can be used to host large files, such as the Prokka DB. Homebrew for example stores its code in GitHub and its bottles of binary executables on Sourceforge.
