### ISSUE TITLE
Option to keep intermediate files

### ISSUE THREAD

**Issue by sjackman** [Victorian-Bioinformatics-Consortium/prokka#13]
I'd like to inspect the `.bls` file for debugging (trying to track down some missing genes found by MAKER-P). I've disabled `delfile( $faa_name, $bls_name);`. A command line option for this purpose would be useful. 

https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L934

**Comment by tseemann** [comment]
This is a good idea.  I've added a ``--debug``` switch which prevents ```delfile()``` from deleting when ```--debug``` is enabled.

I've also ensured the input (.faa) and output (.blast .hmmer3) files are uniquely named now.

**Comment by sjackman** [comment]
Thanks, Torsten.

**Comment by sjackman** [comment]
For what it's worth, GCC calls this option `--save-temps`.
