### ISSUE TITLE
Overly long locustag/prefix results in bad GenBank LOCUS lines

### ISSUE THREAD

**Issue by peterjc** [Victorian-Bioinformatics-Consortium/prokka#32]
Prokka 1.10 can produce broken GenBank output with over-long identifiers in the LOCUS lines.

Sample input (anonymised since this is for a collaborator):

```
/opt/prokka-1.10/bin/prokka --outdir XYZ123draft2_prokka --prefix XYZ123draft2 --locustag XYZ123draft2 --compliant --kingdom Bacteria --gram neg --genus ... --species ... --strain XYZ123 --quiet XZY123_draft2.fasta
```

Sample output:

```
$ grep LOCUS XYZ123draft2.gbk 
LOCUS       XYZ123draft2_contig000001119615 bp   DNA   linear       19-AUG-2014
LOCUS       XYZ123draft2_contig000002170983 bp   DNA   linear       19-AUG-2014
...
```

The LOCUS identifier is too long for the strict GenBank format, and there is no white space between the (truncated) identifier and the sequence length, meaning for example Biopython complains.

Possible output with truncation (not ideal) to ensure a white space would be something like this:

```
$ grep LOCUS XYZ123draft2.gbk 
LOCUS       XYZ123draft2_contig0000 1119615 bp   DNA   linear       19-AUG-2014
LOCUS       XYZ123draft2_contig0000 2170983 bp   DNA   linear       19-AUG-2014
...
```

Possible output abusing the LOCUS line (also not ideal, but some parsers will cope):

```
$ grep LOCUS XYZ123draft2.gbk 
LOCUS       XYZ123draft2_contig000001 1119615 bp   DNA   linear       19-AUG-2014
LOCUS       XYZ123draft2_contig000002 2170983 bp   DNA   linear       19-AUG-2014
...
```

Expected output: Fail early complaining about the overly long identifiers which will cause problems, specifying which option should be changed.

**Comment by tseemann** [comment]
I made a contig with an ID 62 characters long:

    abcdefghijklmnopqrstuvqxyz1234567890ABCDEFGHIJKLMOPQRSTUVWXYZ

After tbl2asn the .SQN file had converted it in different ways:

    str "abcdefghijklmnopqrstuvqxyz1234567890ABCDEFGHIJKLMOPQRSTUVWXYZ" }
    str "abcdefghijklmnopqrstuvqxyz1234567890ABCDEFGHIJK_1" }

The .GBK file ended up like this:

    LOCUS       abcdefghijklmnopqrstuvqxyz1234567890A>660 bp   DNA linear

With the > sign there. Unfortunately it didn't output the other 5 contigs!

**Comment by tseemann** [comment]
I've changed the warning into an error if the contig name is longer than 38 characters:

```
[15:58:18] Contig ID must <= 38 chars long: abcdefghijklmnopqrstuvqxyz1234567890ABCDEFGHIJKLMOPQRSTUVWXYZ
[15:58:18] Please rename your contigs or use --centre XXX to generate clean contig names.
```

**Comment by tseemann** [comment]
Finally found the spec in section 3.4.4 of ftp://ftp.ncbi.nih.gov/genbank/gbrel.txt

This implies the locus name may only be 16 characters long:

```
Positions  Contents
---------  --------
01-05      'LOCUS'
06-12      spaces
13-28      Locus name
29-29      space
30-40      Length of sequence, right-justified
41-41      space
42-43      bp
44-44      space
45-47      spaces, ss- (single-stranded), ds- (double-stranded), or
           ms- (mixed-stranded)
48-53      NA, DNA, RNA, tRNA (transfer RNA), rRNA (ribosomal RNA), 
           mRNA (messenger RNA), uRNA (small nuclear RNA).
           Left justified.
54-55      space
56-63      'linear' followed by two spaces, or 'circular'
64-64      space
65-67      The division code
68-68      space
69-79      Date, in the form dd-MMM-yyyy (e.g., 15-MAR-1991)
```

**Comment by tseemann** [comment]
Although the LOCUS is limited to 16 characters in the spec, the LENGTH  is right-justified and given 11 characters. Because contigs in Bacteria are rarely more than 10Mbp, it only uses 7 of those, leaving 4 extra for the LOCUS. tbl2asn seems to honour this. I'm going to set my MAXCONTIGIDLEN to 20.

**Comment by peterjc** [comment]
20 sounds like a reasonable compromise - thanks!

**Comment by flannsmith** [comment]
I suggest changing the error log output to prompt LOCUS character length must be <=16 as opposed to the <=37 it currently is. Thanks!
