### ISSUE TITLE
Minor .gbk file issues

### ISSUE THREAD

**Issue by cnightwing** [Victorian-Bioinformatics-Consortium/prokka#36]
The LOCUS entries in the .gbk file don't put a space in between the name of the contig (in this case) and its size, which means BioPerl gets upset when it tries to read the file.
Additionally, it would be helpful if there was a default entry for the ACCESSION and VERSION fields, just a '.' would do, as other programs read the file incorrectly when these entries are blank (such as pmauve).

**Comment by tseemann** [comment]
Mauve 2.4.0 is now using an updated BioJava module which solves some of the problems.

Prokka 1.11-dev has checks to ensure the IDs are less than the 38 characters to avoid banging into the sequence length part of the LOCUS line.
