### ISSUE TITLE
New/Customized HMM Databases

### ISSUE THREAD

**Issue by chandni177** [Victorian-Bioinformatics-Consortium/prokka#44]
Hi,
I've been using Prokka a bit with the default options and databases. I recently added the vFAM HMM database in /opt/prokka/db/hmm. After indexing, it was recognized successfully (prokka --listdb).
However, upon running Prokka, I see (from the log) that hmmer3 runs only for the default HMM databases (Pfam,CLUSTERS,HAMAP). Is there any way to confirm that the Prokka run actually used the new database?
Also, we work mostly on metagenomics projects so we are really looking forward to the kingdom=ALL option from the To-Do list.

Thank you,
Chandni

**Comment by tseemann** [comment]
For Issue #35 I made this chage https://github.com/Victorian-Bioinformatics-Consortium/prokka/commit/31efd38ae8322d03614c1f727cb5b65f15b7c4ee which may be of interest to you.
