### ISSUE TITLE
Prokka reorders contigs

### ISSUE THREAD

**Issue by jhawkey** [Victorian-Bioinformatics-Consortium/prokka#46]
If you give prokka a contig set, ordered by reference, it reorders the contigs in the output genbank alphabetically. Would be nice if preserved the original contig order (preferably without renaming the contigs? We submit contigs with genbank format friendly names)

**Comment by tseemann** [comment]
@jhawkey and @elximo sorry for the slow reply!

This is indeed a very annoying "feature" of Prokka. I've fixed it in #46 in the git version. It should also speed up Prokka a bit for projects with 1000s of contigs.
