### ISSUE TITLE
Batch run issues

### ISSUE THREAD

**Issue by AyshwaryaS** [Victorian-Bioinformatics-Consortium/prokka#49]
Thanks for the great software! I have several files to be processed. Running PROKKA on them either serially individually or in batches of say 10 or 50 or 100 often results in partially completed outputs (> 80% of inputs are incomplete). The most common error is:

Could not run command: cat ~/proteins\.faa | parallel --gnu -j 8 --block 943 --recstart '>' --pipe hmmscan --noali --notextw --acc -E 1e-06 --cpu 1 ~/tools/prokka/prokka-1.10/bin/../db/hmm/CLUSTERS.hmm /dev/stdin > ~/proteins\.bls 2> /dev/null

Output directories usually have only the final *fna completed.

Any suggestions? Many thanks for your time and efforts.

**Comment by efr3m** [comment]
@tseemann, I also want to thank you for the great program.

I used to run it in a Biolinux 8 Virtual machine and I never had big problems.

Now I installed Biolinux 8 directly on my machine I always get the same error message reported by @AyshwaryaS  :
`Could not run command: cat B98C39_SA\/proteins\.faa | parallel --gnu --plain -j 8 --block 34594 --recstart '>' --pipe hmmscan --noali --notextw --acc -E 1e-06 --cpu 1 /usr/local/lib/prokka-master/bin/../db/hmm/HAMAP.hmm /dev/stdin > B98C39_SA\/proteins\.bls 2> /dev/null`

Any suggestion how I could fix this issue?

**Comment by aleimba** [comment]
Hi @efr3m,
issue #61 might help.

**Comment by efr3m** [comment]
Great thanks a lot @aleimba.
I downloaded the softawer from http://www.vicbioinformatics.com/software.prokka.shtml now.
All the test to check if the program works were passed, but I cannot create dbs.

' prokka --setupdb
[15:36:51] Cleaning databases in /usr/local/lib/prokka-1.10/bin/../db
[15:36:51] Cleaning complete.
[15:36:51] Looking for 'makeblastdb' - found /usr/bin/makeblastdb
[15:36:51] Determined makeblastdb version is 2.2
[15:36:51] Making kingdom BLASTP database: /usr/local/lib/prokka-1.10/bin/../db/kingdom/Archaea/sprot
[15:36:51] Running: makeblastdb -dbtype prot -in \/usr\/local\/lib\/prokka\-1\.10\/bin\/\.\.\/db\/kingdom\/Archaea\/sprot -logfile /dev/null
[15:36:52] Could not run command: makeblastdb -dbtype prot -in \/usr\/local\/lib\/prokka\-1\.10\/bin\/\.\.\/db\/kingdom\/Archaea\/sprot -logfile /dev/null`

Even though the I have the `/usr/local/lib/prokka-1.10/db/kingdom/Archaea/sprot` file and my `makeblastdb` runs fine.
What am I missing here?

**Comment by aleimba** [comment]
runs fine on my BL8. With your normal user you normally don't have write permissions in */usr/local/lib* (and shouldn't), thus `makeblastdb` can't run.
I recommend putting Prokka in your home, e.g. create a *bin* dir in your home and softlink the binary (adapt the commands as needed):
```bash
cd ~
mkdir bin && cd bin
mv prokka*.tar.gz  ~/bin
tar xvfz prokka*.tar.gz
ln -s /prokka-1.10/bin/prokka prokka
```
Then put the *~/bin* folder in your PATH by writing this line in your *~/.bashrc*:
export PATH=$PATH:$HOME/bin

HTH

**Comment by efr3m** [comment]
thanks for the advice.
It worked now, I think the original issue was indeed the db/hmm

**Comment by tseemann** [comment]
I think @aleimba is correct in that it sounds like a linux user permissions issue.

I'm glad you sorted it out @efr3m !
