### ISSUE TITLE
Bug for option '--hypo' in 'prokka-genbank_to_fasta_db'

### ISSUE THREAD

**Issue by aleimba** [Victorian-Bioinformatics-Consortium/prokka#53]
Option **--hypo** in `prokka-genbank_to_fasta_db` doesn't work.

Line 41 (https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka-genbank_to_fasta_db#L41) has to be changed from:
```perl
next if $prod eq 'hypothetical protein';
```
to
```perl
next if !$hypo and $prod eq 'hypothetical protein';
```

**Comment by tseemann** [comment]
Good pickup!
