### ISSUE TITLE
*.faa result files methionine/stop codon

### ISSUE THREAD

**Issue by aleimba** [Victorian-Bioinformatics-Consortium/prokka#54]
The resulting  \*.faa files from Prokka include stop codons '\*' and atypical (non-ATG) start codons don't start with methionine (both **not** NCBI standard). This is remedied by changing line https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka#L1101:
```perl
$faa_fh->write_seq( $p->translate(-codontable_id=>$gcode) );
```
to:
```perl
$faa_fh->write_seq( $p->translate(-codontable_id=>$gcode, -complete => 1) );
```
See BioPerl HOWTO: http://www.bioperl.org/wiki/HOWTO:Beginners#Translating

**Comment by tseemann** [comment]
I think I've implemented most of your changes here.

I'm not 100% sure what happens with -complete=>1 when the gene is partial, for example when we have a start codon but no stop due to it hitting the end of a contig. 

Once again, good pickup on the inconsistent translation code.
