### ISSUE TITLE
prokka running always using rnammer 

### ISSUE THREAD

**Issue by oisky** [Victorian-Bioinformatics-Consortium/prokka#56]
I am running Prokka for annotating several genomes. It worked well till now, but suddenly it starts to look for rnammer that I do not have installed, even though I did not select the flag -rnammer.
Noting change if I type the flag -rnammer.
Should not it use barrnap (which I have installed and running) as defualt?

**Comment by tseemann** [comment]
@oisky 
You said it used to work, then it changed behaviour?  
Did your system change in some way in between those two events?

**Comment by tseemann** [comment]
No response from user in 4 weeks, assuming user error. Happy for them to re-open an Issue when they get more information.
