### ISSUE TITLE
Cannot find a working copy of Aragorn

### ISSUE THREAD

**Issue by idoerg** [Victorian-Bioinformatics-Consortium/prokka#59]
Hi,

All links to Aragorn seem to be dead. Is there are working copy somewhere?

Thanks!

Iddo

**Comment by tseemann** [comment]
The binaries are located in the ```prokka/binaries/linux/ ``` folder.

**Comment by kiwiroy** [comment]
I've just gone through this and although http://mbioserv2.mbioekol.lu.se/ARAGORN/Downloads/ is now responding in a friendly way again I wish I'd checked here to observe that the dependencies are packaged as static binaries . Either way kiwiroy/aragorn@e7a8cc1 is available as a backup as I've taken to storing dependencies in GitHub in the name of reproducibility.

**Comment by tseemann** [comment]
I will try and make it clearer in the docs that the binaries are all included for modern Linux and OSX.
