### ISSUE TITLE
Barrnap not working within Prokka

### ISSUE THREAD

**Issue by dutchscientist** [Victorian-Bioinformatics-Consortium/prokka#60]
I have installed Prokka on Biolinux8 (Ubuntu 14.04 LTS), and all modules except for Barrnap work nicely.  Installed it as described at http://www.vicbioinformatics.com/software.barrnap.shtml

When running Prokka, it finds usr/bin/barrnap, but during run message is:
"No binary for your OS 'linux' is included. If you have one, copy it to /usr/bin/../binaries/linux/nhmmer."

I have copied the nhmmer executable to /usr/bin using sudo cp, but it still gives the error message? I also compiled nhmmer from source, without any effect

**Comment by dutchscientist** [comment]
I think it may be due to the OS detection? When I run nhmmer on the commandline with bac.hmm, it works fine, and it's in the path, so it's seems purely the way the barrnap script calls the executable?

**Comment by tseemann** [comment]
@dutchscientist - does barrnap run by itself? 

    % barrnap contigs.fa

**Comment by dutchscientist** [comment]
Hi Torsten,

yes, it does. That is what confuses me!

cheers
Arnoud

**Comment by tseemann** [comment]
Barrnap (currently) requires that nhmmer be exactly in the barrnap/binaries/linux/ folder, which you must have there, otherwise it wouldn't run.

Type ```which barrnap``` to see where it is.

Then run ```prokka``` and see where *it* finds ```barrnap``` from the .LOG file:
```
[13:57:45] Looking for 'barrnap' - found /home/torsten/.linuxbrew/bin/barrnap
[13:57:45] Determined barrnap version is 0.5
````

Are they the same?

**Comment by dutchscientist** [comment]
That comment ("Barrnap (currently) requires that nhmmer be exactly in the barrnap/binaries/linux/ folder") helped. I had copied barrnap to /usr/bin, removed it from there and then found out that the barrnap directory was absent from the path.

Have finally gotten the prokka and barrnap directories in the path and it works now :)

So thanks!

**Comment by tseemann** [comment]
Great to hear!
