### ISSUE TITLE
No taxonomic annotations provided

### ISSUE THREAD

**Issue by xapple** [Victorian-Bioinformatics-Consortium/prokka#62]
So I have a bunch of contigs (that were assembled from a environmental shotgun metagenome) and would like to have some taxonomical annotations assigned to them. It seems like prokka is a program that can provide this. However, I was not able to retrieve any such information. I have tried different options such as `--usegenus` or `--kingdom Bacteria` or no options at all. Invariably, every sequence in the resulting `.fsa` file will include the following uninformative header:

    >contig-0000001 [gcode=11] [organism=Genus species] [strain=strain]

What is one supposed to do to get taxonomical annotations ?

**Comment by aleimba** [comment]
Prokka is really **not** the right tool for this job, it's for annotating prokaryotic contigs/replicons and that's it.

I'm definitely not an expert on that field, but I think most of the metagenomics crowd use the reads from the NGS machine directly (after QC, adapter trimming etc. of course) to do the taxonomic classification. A good tool for that is Kraken from the Salzberg group (http://ccb.jhu.edu/software/kraken/).

If you want to assign your assembled contigs @nickloman has a blog post including these: http://pathogenomics.bham.ac.uk/blog/2013/08/methods-for-taxonomic-assignment-of-shotgun-whole-genome-metagenomics-reads/

You can also use blobology (which I have used for QC): https://github.com/blaxterlab/blobology

In the end, I recommend to shop around in seqanswers.com, biostar.com, PubMed etc.

**Comment by xapple** [comment]
Hey thanks a lot for the info ! I will check that out.
