### ISSUE TITLE
Add functional data to existing CDS annotations?

### ISSUE THREAD

**Issue by Biomicrogen** [Victorian-Bioinformatics-Consortium/prokka#63]
Is it possible, in Prokka, to use existing ORF annotations (Say from Glimmer3.0 which was trained using an organism close to my ooi (organism of interest)?) and just add the functional data to the CDS annotations?

**Comment by tseemann** [comment]
@Biomicrogen It would be a good feature to enable loading of an existing CDS coordinate annotation and skip the Prodigal step.

Option 1:
Are you able to get the gene predictions into GFF format?
With the sequence IDs in the GFF matching the sequence IDs in the FASTA?
I could then add a "--cdsfromgff" option. 

Option 2:
Could you create a Prodigal training file instead?
I could then get Prodigal to use it instead of the default self training.
There would be a "--prodigal-training-file" type option.

**Comment by Biomicrogen** [comment]
I have annotation tracks from Geneious (glimmer predictions) which I created using a training file (created using a completed annotated genome of an organism phylogenetically close to mine) and I want to add the functional information using Prokka without re-annotating the CDS features as they do not match many times.

 
I could probably export the CDS annotations to a gff file via Geneious.

Also, do you know of a straight forward way to add COG or KEGG identifiers to CDS annotations.  I would like to bin all my CDS (the ones which show homology to known functional orthologs) but biochemical pathway or KEGG numbers at least?

Thanks Torsten


Brandon
 

 

-----Original Message-----

**Comment by tseemann** [comment]
Brandon - does KEGG's KASS service do what you want?

http://www.genome.jp/tools/kaas/

**Comment by tseemann** [comment]
Brandon

You sort of want a combination of annotation transfer (coordinates only) and full annotation (functional assignment), which I never really anticipated with Prokka. I never found Glimmer3 to give good start codon predictions for bacteria, I always had better luck with GeneMarkS and aragorn.

For just annotation transfer there is RATT: http://ratt.sourceforge.net/

**Comment by Biomicrogen** [comment]
Thanks for your fast response!  Aragorn did work nicely, though it's hard to compare since I have no functional genomic data for this organism.  I just obtained some RNA-SEQ data which I may be able to map start sites with.  I will give the KAAS pipeline a try, I'm not sure why I didn't see that service in my searches!  It always helps to have a seconds pair of eyes!

Thanks again!

 

Brandon 


 

-----Original Message-----

**Comment by tseemann** [comment]
You probably want to use an annotation pipeline like MAKER which can combine evidence from multiple sources, including existing proteins and RNA-Seq data (BAM files).

http://www.yandell-lab.org/software/maker.html

**Comment by musta1234** [comment]
Hello tseeman,
Is there a way for PROKKA assembly to give me COG numbers for predicted proteins. I saw this exercise but I check my .gff files have no COG #. Is there a way to re-annotate the genomes and get COG#?
 Prokka 1.11 on BioLinux 8
Many thanks ,
Musta1234
http://metagenomics-workshop.readthedocs.org/en/latest/functional-annotation/minpath.html

**Comment by aleimba** [comment]
COG annotation is not yet implemented, but might come in a future version: #85.

**Comment by musta1234** [comment]
Thanks, Aleimba
