### ISSUE TITLE
'--proteins' needs to strip gene numbering, "_#", from reference gene names

### ISSUE THREAD

**Issue by aleimba** [Victorian-Bioinformatics-Consortium/prokka#67]
When using option **--proteins** for annotation with a reference, reference paralog gene numbering "\_#" (e.g.: arcA\_1) needs to be stripped before annotation transfer. Otherwise, you'll have gene tags including "\_#" when it's not a paralogous gene, or even constructs like "ydef\_1\_1".
On a related issue see #31.

**Comment by tseemann** [comment]
I've added some code to strip the _N suffix before deduplicating them: e48673321048853c7d93cb4184e9ca88fba145ca

Thanks for pointing this out! I never considered people feeding Prokka .gbk back into --proteins.

See also new feature where --proteins can accept a .GBK file directly: 5c2923e34fb9f953c2c0497b02a46b29c47deb52
