### ISSUE TITLE
Adding RNAseq evidence to PROKKA

### ISSUE THREAD

**Issue by ernestopicardi** [Victorian-Bioinformatics-Consortium/prokka#68]
Hi,
is there a way to include RNAseq evidence to prokka? I mean something like read alignments in BLAST tabular format or wig or similar.
Thanks a lot in advance,
Ernesto

**Comment by tseemann** [comment]
No there isn't, and probably won't be any in this version.

I would recommend trying MAKER: http://www.yandell-lab.org/software/maker.html
