### ISSUE TITLE
Order of features in GFF file incorrect

### ISSUE THREAD

**Issue by marchoeppner** [Victorian-Bioinformatics-Consortium/prokka#69]
Hi,

I noticed that using the 'addgenes' option creates somewhat unordered gff files - the GFF convention states ( am guessing) that features should be printed following their hierarchy - i.e. genes -> mRNAs -> CDS/exon. At the moment Prokka prints the CDS first, then the gene. 

On that note, if genes can be added in, shouldn't mRNAs too? 

Cheers,
Marc

**Comment by marchoeppner** [comment]
I hope it's ok to add to this list, since they issues are all related to the addgenes option:

- Gene features should have an 'ID' tag and CDS (or other children) should reference the gene ID via a 'Parent' tag (http://www.sequenceontology.org/gff3.shtml)
- Gene feature seq_id seems broken, since it writes 'SEQ' instead of the actual name of the contig (works for the CDS feature though, so not sure where in the code this breaks, couldn't find it just now).

**Comment by tseemann** [comment]
Marc / @marchoeppner 

Thanks for taking the time to bring these things to my attention. Most people don't seem to use the GFF3 file sadly, so I don't get much feedback on it:

1. I think the SEQ problem was fixed a while back: https://github.com/Victorian-Bioinformatics-Consortium/prokka/issues/7  
What version of Prokka are you using?

2. You are right that the gene should have and ID, and the CDS should connect to it via the Parent tag. I have fixed that now.

3, For eukaryotes the canonical GFF gene does have gene > mRNA -> exon(s) -> CDS but for Bacteria the convention tends to be gene -> CDS only. This is what Genbank do for all their GFF files produced by the NCBI annotwriter for bacterial genomes. I guess as we get better at using RNA-Seq etc to determine TSS and UTRs and promoters they may use the full gene model.

4. As I understand it, the features can appear in any order. There is a special '###' directive to tell the parser it is safe to not expect any more links etc.  But I can't find absolute wording anywhere. Do you have a reference for that? I want to be compliant.
