### ISSUE TITLE
prokka-uniprot_to_fasta_db, --maxlen help mistake

### ISSUE THREAD

**Issue by aleimba** [Victorian-Bioinformatics-Consortium/prokka#74]
There's a tiny mistake in `prokka-uniprot_to_fasta_db`. In line https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/bin/prokka-uniprot_to_fasta_db#L109 option *-maxlen* has "Minimum" as description instead of "Maximum":
```Perl
{OPT=>"maxlen=i", VAR=>\$maxlen, DEFAULT=>1E5, DESC=>"Maximum peptide length"},
```

**Comment by tseemann** [comment]
Thanks again :+1:
