### ISSUE TITLE
*.err file is correct?

### ISSUE THREAD

**Issue by danbacastro** [Victorian-Bioinformatics-Consortium/prokka#77]
Hello everybody,

I'm using prokka with two genomes recovered from metagenomes. Prokka produces all files and they seem correct, but the .err file has always some messages that worry  me.

Here is the first 20 lines of one of the .err files:

Discrepancy Report Results

Summary
FATAL: MISSING_PROTEIN_ID:3838 proteins have invalid IDs.
DISC_SOURCE_QUALS_ASNDISC:strain (all present, all same)
DISC_SOURCE_QUALS_ASNDISC:taxname (all present, all same)
DISC_FEATURE_COUNT:CDS: 3838 present
DISC_FEATURE_COUNT:tRNA: 36 present
DISC_FEATURE_COUNT:repeat_region: 2 present
DISC_FEATURE_COUNT:tmRNA: 1 present

The file continues, it has around 16000 lines.

I'm running prokka as the following:

prokka --outdir g.test.prokka --cpus 8 --rnammer g.fasta

Do I need to worry about the .err files?

Best regards,

Daniel

**Comment by aleimba** [comment]
Hi @danbacastro,

the *.err file is the discrepancy report from NCBI's [`tbl2asn`](http://www.ncbi.nlm.nih.gov/genbank/tbl2asn2) tool. Prokka uses `tbl2asn` to create the *.gbk, *.sqn ... files. The FATAL errors are only important if you want to use the *.sqn file directly for a submission to NCBI:
http://www.ncbi.nlm.nih.gov/genbank/asndisc

HTH,
Andreas

**Comment by tseemann** [comment]
@danbacastro 
@aleimba is correct. No need to worry about it. Using ```--compliant``` _might_ get rid of that "FATAL" warning, not sure. But it doesn't matter.
