### ISSUE TITLE
.gbk output not readable by artemis

### ISSUE THREAD

**Issue by russianconcussion** [Victorian-Bioinformatics-Consortium/prokka#84]
Hi, thanks for the wonderful annotation tool.  It's great to be able to rely something local (and customizable!) when the RAST servers are constipated.  When I try to open the .gbk output from  prokka 1.7.2 using artemis, it says there is no sequence information.  I cannot read it into BioPython with SeqIO, either.  Do you know why this is?  The gff is perfectly readable.

**Comment by aleimba** [comment]
first, you're using a quite old version or Prokka. There's been lots of bug fixes and new features (https://github.com/Victorian-Bioinformatics-Consortium/prokka/blob/master/doc/ChangeLog.txt), thus I recommend to go for the newest stable release v1.11 (http://www.vicbioinformatics.com/software.prokka.shtml).
Did you have a look at the GENBANK file in an editor? Is sequence present or not? Did Prokka give you any errors while running (should also be in *.log)?
The GENBANK file is created by NCBI's `tbl2asn` during the Prokka run, while the GFF file is created from the main Prokka script directly. Hence, there might be a posibility that `tbl2asn` didn't run correctly.

**Comment by russianconcussion** [comment]
Thanks! I updated tbl2asn and prokka and it works fine now. In addition, prokka identified CRISPRs for me! What a great piece of software!

**Comment by tseemann** [comment]
@aleimba Should probably add some sort of check to see if the user's tbl2asn has expired or not.

**Comment by aleimba** [comment]
@tseemann yep, good idea!
